server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/{{PROJECT_NAME}}_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: your-super-secret-jwt-key-change-in-production
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.{{PROJECT_NAME}}: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG